#!/bin/bash

# Example usage: 
# ./qswrapper gpu-troja.q@tdll2 3 'echo ahoj'
#
# by Dominik 

# Specify one particular machine, on which the job must be run. It's assumed that all the jobs run on the same machine and no checks are implemented.
QMACHINE=$1 ## e.g. gpu-troja.q@tdll2, no gpu-\* or gpu-ms.q@dll[2345] !!!
NUM=$2  ## e.g. 3
shift
shift
CMD="$@" ## the other parameters are the command to run
echo "$CMD"

# from here: https://gist.github.com/earthgecko/3089509
HASH=qswrapper-`cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 8 | head -n 1`

mkdir -p .$HASH  # the temporary files are in .$HASH directory

# run $NUM jobs, $NUM-1 will wait and the last one launches the command
for i in `seq $NUM`; do
	qsubmit -q $QMACHINE -gpus=1 -jobname=${QMACHINE/*@}-$i.$NUM "./qsjobwrapper.sh $HASH $i $NUM $CMD" | tee >( cut -f 3 -d' ' > .$HASH/$i.$NUM.jobid ) || exit 1
done

